services:
  - type: web
    name: ilbuco
    runtime: static
    buildCommand: echo "No build required"
    staticPublishPath: ./public
    pullRequestPreviewsEnabled: true # optional
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
